### ISSUE TITLE
Test with Cluster workload fails 

### ISSUE THREAD

**Issue by aruneshchandra** [Node-DC/Node-DC-EIS#10]
C:\git\Node-DC-EIS\Client\Node-DC-EIS-client>python runspec.py

[21-02-2017 12:00:55] Parsing arguments.
Input options config files: None
Starting NODE-DC-EISv0.9 in Cluster Mode
[21-02-2017 12:00:55] Setting up log directory.
[21-02-2017 12:00:55] Loading database with 10000 records.
In progress...
[21-02-2017 12:01:24] Loading database done.
[21-02-2017 12:01:24] Checking the number of records in the DB.
[21-02-2017 12:01:24] Database consistent-DB record count okay.
[21-02-2017 12:01:24] Build list of employee IDs.
[21-02-2017 12:01:24] Build list of employee IDs done.
[21-02-2017 12:01:24] Build list of employee last names.
[21-02-2017 12:01:24] Build list of employee last names done.
[21-02-2017 12:01:24] Build list of address zipcodes.
[21-02-2017 12:01:25] Build list of address zipcode done.
[21-02-2017 12:01:25] Building list of Urls
[21-02-2017 12:01:25] Building list of Urls done.
[21-02-2017 12:01:25] Sending requests
Traceback (most recent call last):
  File "runspec.py", line 977, in <module>
    arg_parse()
  File "runspec.py", line 340, in arg_parse
    get_data()
  File "runspec.py", line 429, in get_data
    send_request(employee_idlist)
  File "runspec.py", line 658, in send_request
    run_printenv(log)
  File "runspec.py", line 351, in run_printenv
    print >> log, "# requests    :", request +"  (Default value = 10000)"
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by priyankasprakash** [comment]
Hi Arunesh,

Here is the PR with the fix for this issue. Let me know if it resolves the issue- https://github.com/Node-DC/Node-DC-EIS/pull/11. You can also run using config.json file for default configuration. (python runspec.py -f config.json)

**Comment by aruneshchandra** [comment]
This fixes the problem I was having. Thanx.
