### ISSUE TITLE
Default version of Mongoose that gets downloaded throws connection errors on Windows

### ISSUE THREAD

**Issue by yweijiang** [Node-DC/Node-DC-EIS#9]
Seeing many errors of the following form occur when running using default version of Mongoose on Windows server:

{ MongoError: connection 3 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\error.js:29:11)
    at Socket.<anonymous> (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\connection\connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  name: 'MongoError',
  message: 'connection 3 to 127.0.0.1:27017 timed out' }
Saving Health: Internal error while saving employee record
Error while running async.seriesMongoError: connection 3 to 127.0.0.1:27017 timed out
{ MongoError: connection 3 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\error.js:29:11)
    at Socket.<anonymous> (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\connection\connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  name: 'MongoError',
  message: 'connection 3 to 127.0.0.1:27017 timed out' }
Saving Health: Internal error while saving employee record
Error while running async.seriesMongoError: connection 3 to 127.0.0.1:27017 timed out
{ MongoError: connection 3 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\error.js:29:11)
    at Socket.<anonymous> (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\connection\connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  name: 'MongoError',
  message: 'connection 3 to 127.0.0.1:27017 timed out' }
Saving Photo: Internal error while saving employee record
Error while running async.seriesMongoError: connection 3 to 127.0.0.1:27017 timed out
{ MongoError: connection 3 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\error.js:29:11)
    at Socket.<anonymous> (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\connection\connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  name: 'MongoError',
  message: 'connection 3 to 127.0.0.1:27017 timed out' }
Saving Photo: Internal error while saving employee record
Error while running async.seriesMongoError: connection 3 to 127.0.0.1:27017 timed out
{ MongoError: connection 3 to 127.0.0.1:27017 timed out
    at Function.MongoError.create (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\error.js:29:11)
    at Socket.<anonymous> (C:\Node-DC-EIS\Node-DC-EIS-cluster\node_modules\mongodb-core\lib\connection\connection.js:186:20)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  name: 'MongoError',
  message: 'connection 3 to 127.0.0.1:27017 timed out' }
Saving Photo: Internal error while saving employee record
Error while running async.seriesMongoError: connection 3 to 127.0.0.1:27017 timed out

Changing the version of Mongoose in package.json to '4.7.1' fixes this issue most of the time.

**Comment by uttampawar** [comment]
@yweijiang,
Does version changes (downgrade to 4.7.1), an acceptable solution?

**Comment by yweijiang** [comment]
@uttampawar
Yes, this should be a good solution.

**Comment by uttampawar** [comment]
@priyankasprakash Should we consider downgrading mongoose driver as a valid solution and close this issue or is there a better option to solve this issue?

**Comment by priyankasprakash** [comment]
Mongoose version has already been downgraded for cluster mode. I will make the same changes for micro-services and submit a patch.

**Comment by uttampawar** [comment]
Closing this issue, since we don't see this error after our workaround of downgrading mongoose version and the fix is outside our control. We can reopen this issue if there is a need.
